### PR TITLE
Revert "Revert "PIN-3334 Errore query su DocumentDB quando viene passata una wildcard""

### PR DESCRIPTION
**Pull request by galales**
Reverts pagopa/interop-be-purpose-process#156

Re-creating this PR because it needs further discussion

### CODE REVIEW

**Comment by galales** [comment]
see [this comment](https://github.com/pagopa/interop-be-purpose-process/pull/155#issuecomment-1539660149) to proceed with the discussion

**Comment by TonioGela** [comment]
> see [this comment](https://github.com/pagopa/interop-be-purpose-process/pull/155#issuecomment-1539660149) to proceed with the discussion

About the question you asked in the comment, let's check whether some high-level services like BFF, APIGW, or the front end use the regex feature. If they don't, removing the support for regexes altogether is better, as we'll offer a stricter API that won't escape our control. I don't think that we will need regex support for searches soon to be fair.

**Review by TonioGela — APPROVED** [review]

**Comment by galales** [comment]
No more required

**Comment by TonioGela** [comment]
👋

**Pull request closed without merging**
